config/routes.rb
Registration::Application.routes.draw do
  resources :parents

  resources :racers

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :phone1, :phone2

  has_many :racers

  validates :firstname, :length => { :maximum => 45, :minimum => 2 }
  validates :lastname, :length => { :maximum => 45, :minimum => 2 }
  validates :phone1, :length => { :maximum => 12, :minimum => 7 }

end

app/models/racer.rb
class Racer < ActiveRecord::Base
  attr_accessible :city, :dob, :email, :emergencyphone, :firstname, :gender, :lastname, :phone1, :phone2, :racerlevel, :state, :street1, :street2, :zipcode

  belongs_to :parent

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parents }
    end
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
    @parent = Parent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parent }
    end
  end

  # GET /parents/new
  # GET /parents/new.json
  def new
    @parent = Parent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parent }
    end
  end

  # GET /parents/1/edit
  def edit
    @parent = Parent.find(params[:id])
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(params[:parent])

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render json: @parent, status: :created, location: @parent }
      else
        format.html { render action: "new" }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parents/1
  # PUT /parents/1.json
  def update
    @parent = Parent.find(params[:id])

    respond_to do |format|
      if @parent.update_attributes(params[:parent])
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent = Parent.find(params[:id])
    @parent.destroy

    respond_to do |format|
      format.html { redirect_to parents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @racers }
    end
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
    @racer = Racer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @racer }
    end
  end

  # GET /racers/new
  # GET /racers/new.json
  def new
    @racer = Racer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @racer }
    end
  end

  # GET /racers/1/edit
  def edit
    @racer = Racer.find(params[:id])
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(params[:racer])

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render json: @racer, status: :created, location: @racer }
      else
        format.html { render action: "new" }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /racers/1
  # PUT /racers/1.json
  def update
    @racer = Racer.find(params[:id])

    respond_to do |format|
      if @racer.update_attributes(params[:racer])
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer = Racer.find(params[:id])
    @racer.destroy

    respond_to do |format|
      format.html { redirect_to racers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/racers_helper.rb
module RacersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Registration</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<h1>Listing parents</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parents.each do |parent| %>
  <tr>
    <td><%= parent.firstname %></td>
    <td><%= parent.lastname %></td>
    <td><%= parent.phone1 %></td>
    <td><%= parent.phone2 %></td>
    <td><%= link_to 'Show', parent %></td>
    <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
    <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @parent.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @parent.lastname %>
</p>

<p>
  <b>Phone1:</b>
  <%= @parent.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @parent.phone2 %>
</p>


<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/racers/_form.html.erb
<%= form_for(@racer) do |f| %>
  <% if @racer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

      <ul>
      <% @racer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :street1 %><br />
    <%= f.text_field :street1 %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :emergencyphone %><br />
    <%= f.text_field :emergencyphone %>
  </div>
  <div class="field">
    <%= f.label :racerlevel %><br />
    <%= f.text_field :racerlevel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/racers/edit.html.erb
<h1>Editing racer</h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<h1>Listing racers</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Street1</th>
    <th>Street2</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Gender</th>
    <th>Dob</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th>Email</th>
    <th>Emergencyphone</th>
    <th>Racerlevel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @racers.each do |racer| %>
  <tr>
    <td><%= racer.firstname %></td>
    <td><%= racer.lastname %></td>
    <td><%= racer.street1 %></td>
    <td><%= racer.street2 %></td>
    <td><%= racer.city %></td>
    <td><%= racer.state %></td>
    <td><%= racer.zipcode %></td>
    <td><%= racer.gender %></td>
    <td><%= racer.dob %></td>
    <td><%= racer.phone1 %></td>
    <td><%= racer.phone2 %></td>
    <td><%= racer.email %></td>
    <td><%= racer.emergencyphone %></td>
    <td><%= racer.racerlevel %></td>
    <td><%= link_to 'Show', racer %></td>
    <td><%= link_to 'Edit', edit_racer_path(racer) %></td>
    <td><%= link_to 'Destroy', racer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Racer', new_racer_path %>

app/views/racers/new.html.erb
<h1>New racer</h1>

<%= render 'form' %>

<%= link_to 'Back', racers_path %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @racer.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @racer.lastname %>
</p>

<p>
  <b>Street1:</b>
  <%= @racer.street1 %>
</p>

<p>
  <b>Street2:</b>
  <%= @racer.street2 %>
</p>

<p>
  <b>City:</b>
  <%= @racer.city %>
</p>

<p>
  <b>State:</b>
  <%= @racer.state %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @racer.zipcode %>
</p>

<p>
  <b>Gender:</b>
  <%= @racer.gender %>
</p>

<p>
  <b>Dob:</b>
  <%= @racer.dob %>
</p>

<p>
  <b>Phone1:</b>
  <%= @racer.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @racer.phone2 %>
</p>

<p>
  <b>Email:</b>
  <%= @racer.email %>
</p>

<p>
  <b>Emergencyphone:</b>
  <%= @racer.emergencyphone %>
</p>

<p>
  <b>Racerlevel:</b>
  <%= @racer.racerlevel %>
</p>


<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>